# Generated by Django 4.2.24 on 2025-09-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramMedia',
        ),
    ]
