# Generated by Django 4.2.24 on 2025-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_instagrammedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Main image displayed on the homepage (recommended size: 1920x1080px)', upload_to='homepage/')),
                ('is_active', models.BooleanField(default=True, help_text='Set this configuration as active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Configuration',
                'verbose_name_plural': 'Home Page Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['category', 'price'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['order'], 'verbose_name': 'Portfolio Image', 'verbose_name_plural': 'Portfolio Images'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_responded',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='published',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='is_contacted',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service_interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True, help_text='List features separated by new lines', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in KES', max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('lifestyle', 'Lifestyle'), ('commercial', 'Commercial')], default='fashion', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('lifestyle', 'Lifestyle'), ('commercial', 'Commercial')], default='fashion', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ImageField(upload_to='portfolio/main/'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
