# Generated by Django 5.0.14 on 2025-09-08 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_galleryimage_options_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IMA ANA Portfolio', max_length=100)),
                ('site_description', models.TextField(default='Digital Creator & Professional Model')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@lcmukiri?_t=ZM-8zYQ4OgHYE2&_r=1', help_text='TikTok profile URL')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Business address')),
                ('hero_title', models.CharField(default='IMA ANA', max_length=100)),
                ('hero_subtitle', models.CharField(default='Digital Creator & Professional Model', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='HomePageConfig',
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Profile Image', 'verbose_name_plural': 'Profile Images'},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='service_interest',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='status',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_responded',
            field=models.BooleanField(default=False, help_text='Mark as responded once you have replied to this message.'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the package.', null=True, upload_to='packages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='published',
            field=models.BooleanField(default=True, help_text='Set to False to hide this item from the public site.'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='is_contacted',
            field=models.BooleanField(default=False, help_text='Mark as contacted once you have responded to this request.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to hide this image from the gallery.'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from filename', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('digital', 'Digital Creator'), ('modelling', 'Modelling')], default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to hide this package from the public site.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('digital', 'Digital Creator'), ('modelling', 'Modelling')], default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured to display on the homepage.'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image for the portfolio item.', upload_to='portfolio/main_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
