# Generated by Django 5.0.14 on 2025-09-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='main_profile_image',
            field=models.ForeignKey(blank=True, help_text='Select the main profile image to display across the site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.profileimage'),
        ),
    ]
