# Generated by Django 5.0.14 on 2025-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_sitesettings_main_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service_interest',
            field=models.CharField(blank=True, help_text='Service of interest', max_length=100),
        ),
    ]
